### ISSUE TITLE
Search data by name + id

### ISSUE THREAD

**Issue by evajacobs** [oSoc18/Octotrails#1]
## Description 

Search for stops based on name or technical ID

## Route

`/stops/search?by=(stop_name|stop_id)&term=(term of search)`

## Parameters

- `by` : What the search is about

- `term` : What do we search 

## Validations

- [x] The query parameters `by` and `term` **must be defined**. 

- [x] The query parameter `by` can only take as value `name` or `tech_id`

## Errors

The following status are the response status if an error appears :

- [x] `404`  : If query parameters `by` or `term` are missing or empty.

- [x] The body of the response contains a message about the error.

## Actions

Returns all matching stops

**Comment by jbelien** [comment]
Temporary API : `http://detobel36.ddns.net/files/osoc/stops/name/{name}`
Example : http://detobel36.ddns.net/files/osoc/stops/name/park

*Use this inside BeCentral : https://proxy.sulliops.co/index.php?http://detobel36.ddns.net/files/osoc/stops/name/park*

**Comment by jbelien** [comment]
This is developed by @detobel36.
Feel free to ask him to adapt the API depending on (y)our needs !

**Comment by jbelien** [comment]
I'll reopen this issue so we can continue to talk about the API.

**Comment by jbelien** [comment]
There is an issue with character set !

http://detobel36.ddns.net/files/osoc/stops/name/park returns :

            "id": "4116",
            "alpha_fr": "Parc ?\ufffdlisabeth",
            "alpha_nl": "Elisabeth-park",
            "descr_fr": "PARC ELISABETH",
            "descr_nl": "ELISABETHPARK",
            "coord_x": "4.32833959859851",
            "coord_y": "50.8650717400489",

**Comment by detobel36** [comment]
Can't correct automatically :confused:
Is it a real problem ?  It's here only a "temporary" database...

**Comment by jbelien** [comment]
You should convert your source file to UTF-8.
It is not a blocking issue but it's still an issue. We need to display the stop name in our front-end without messing with what the API returns.

**Comment by detobel36** [comment]
I don't think it's so easy...
The `.dbf` file have been convert with Excel to be an `.csv`.       
Then I have import this file to my PostgreSQL database.           
In the database, the data is in UTF-8, and have already this problem.         
         
I think that the problem is on the first step.

**Comment by detobel36** [comment]
But home I have more access to my server.  Normally I could fixe that tomorrow :wink:

**Comment by jbelien** [comment]
If needed I can convert the DBF file to a well encoded (in UTF-8) CSV file.
