### ISSUE TITLE
Get stop information

### ISSUE THREAD

**Issue by evajacobs** [oSoc18/Octotrails#20]

**Comment by jbelien** [comment]
Temporary API : `http://detobel36.ddns.net/files/osoc/stops/{stop_id}`
Example : http://detobel36.ddns.net/files/osoc/stops/1

*Use this inside BeCentral : https://proxy.sulliops.co/index.php?http://detobel36.ddns.net/files/osoc/stops/1*

**Comment by jbelien** [comment]
This is developed by @detobel36.
Feel free to ask him to adapt the API depending on (y)our needs !
