### ISSUE TITLE
Current user location

### ISSUE THREAD

**Issue by evajacobs** [oSoc18/Octotrails#36]

**Comment by jbelien** [comment]
Documentation : https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

**Comment by jbelien** [comment]
Mapbox GL example I would use to "follow" the current user position : https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-line/

**Comment by jbelien** [comment]
There is the example for the `GeolocateControl` control : https://www.mapbox.com/mapbox-gl-js/example/locate-user/
We don't need the `GeolocateControl` control but I like the "animated" icon for the user location.

**Comment by jbelien** [comment]
To track the use, use `watchPosition()` function instead of `getCurrentPosition()` : https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition
