### ISSUE TITLE
Stops around current user

### ISSUE THREAD

**Issue by evajacobs** [oSoc18/Octotrails#38]

**Comment by jbelien** [comment]
Temporary API : http://detobel36.ddns.net/files/osoc/stops/proximity/{X},{Y}
Example : http://detobel36.ddns.net/files/osoc/stops/proximity/1,1

*Use this inside BeCentral : https://proxy.sulliops.co/index.php?http://detobel36.ddns.net/files/osoc/stops/proximity/1,1*

**Comment by jbelien** [comment]
This is developed by @detobel36.
Feel free to ask him to adapt the API depending on (y)our needs !
