### ISSUE TITLE
Display open street map

### ISSUE THREAD

**Issue by evajacobs** [oSoc18/Octotrails#39]

**Comment by jbelien** [comment]
Do you already have any idea what library you'll use for the map ?

Suggestions (random order) :
- [Leaflet](https://leafletjs.com/)
- [OpenLayers](https://openlayers.org/)
- [Mapbox.js](https://www.mapbox.com/mapbox.js/)
- [Mapbox BGL JS](https://www.mapbox.com/mapbox-gl-js/api/)
- ...
