### ISSUE TITLE
API log in

### ISSUE THREAD

**Issue by evajacobs** [oSoc18/Octotrails#4]
## Description 

Implements a basic login by username &&  password.
The user data is for now hardcoded and looks like :
```js 
const user = {
  mail: 'angular@mean.app',
  password: 'express'
};
```

**Comment by jbelien** [comment]
I think you don't have to worry about logging in ...
Client seemed to agree that can be added afterwards. I wouldn't spend/waste time on this feature.

**Comment by Dakad** [comment]
Okay. 
Plus, it's already implemented on the MEAN stack

**Comment by Dakad** [comment]
Okay.
Plus, it's already implemented on the MEAN stack.
