### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by michieldewilde** [oSoc18/Octotrails#60]
Don't commit `.env` file to your repository.
Create a `.env.example` file with default values and/or empty values where it applies.
In the setup instructions of your readme you should have some section about renaming or copying `.env.example` to file with another name `.env` or `.env.development`.
Secrets (the values in your `.env`) can be shared through a note in Slack or some other system.

Remove the file from the git history by following these [instructions](https://help.github.com/articles/removing-files-from-a-repository-s-history/).

If you can't get this to work, contact a coach who is proficient in Git.

@mietcls can you follow up on this?

**Comment by mietcls** [comment]
@michieldewilde the team is already on it 💃
