### ISSUE TITLE
🍦 ICE CREAM

### ISSUE THREAD

**Issue by evajacobs** [oSoc18/Octotrails#9]

**Comment by jbelien** [comment]
I did some research this weekend :
- Häagen-Dazs : https://www.openstreetmap.org/node/3678495998
- Australian : https://www.openstreetmap.org/node/4413751151
- or the ice cream truck near the station of course

🍦

**Comment by jbelien** [comment]
Sorry guys, oSoc is over, no more ice creams 😢
